<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="ESLDellV3" name="signInAction.TC_Login" tests="4" failures="0" timestamp="04 May 2018 12:31:32 GMT" time="0.061" errors="1">
  <testcase name="examinationResultSanityTest" time="0.000" classname="signInAction.TC_Login">
    <skipped/>
  </testcase> <!-- examinationResultSanityTest -->
  <testcase name="ExamConfigMasterTest" time="0.000" classname="signInAction.TC_Login">
    <skipped/>
  </testcase> <!-- ExamConfigMasterTest -->
  <testcase name="LoginWithMultipleUser" time="0.000" classname="signInAction.TC_Login">
    <skipped/>
  </testcase> <!-- LoginWithMultipleUser -->
  <testcase name="startTest" time="0.061" classname="signInAction.TC_Login">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat testBase.TestBase.getUrl(TestBase.java:111)at testBase.TestBase.init(TestBase.java:65)at signInAction.TC_Login.startTest(TC_Login.java:53)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.TestRunner.beforeRun(TestRunner.java:529)at org.testng.TestRunner.run(TestRunner.java:497)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)]]>
    </error>
  </testcase> <!-- startTest -->
</testsuite> <!-- signInAction.TC_Login -->
